name: pycml_env

dependencies: 
  - python 
  - numpy 
  - toolz 
  - matplotlib 
  - pandas 
  - pyproj 
  - cython 
  - -c scitools cartopy
  - pip: 
    - git+https://bitbucket.org/cchwala/pycomlink.git 
