name: pycml_env
channels:
  - conda-forge
dependencies: 
  - python=2.7 
  - numpy 
  - toolz 
  - matplotlib 
  - pandas 
  - pyproj 
  - cython
  - gdal
  - geos
  - proj.4
  - seaborn
  - anaconda 
  - cartopy
  - pip: 
    - git+https://bitbucket.org/cchwala/pycomlink.git 
