name: pycml_env

dependencies: 
  - python 
  - numpy 
  - toolz 
  - matplotlib 
  - pandas 
  - pyproj 
  - pip: 
    - git+https://github.com/SciTools/cartopy.git@master#egg=cartopy
    - git+https://bitbucket.org/cchwala/pycomlink.git 
